# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/mengb/arch/Exp6/Exp6.srcs/sources_1/ip/divider/divider.xci
# IP: The module: 'divider' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/mengb/arch/Exp6/Exp6.srcs/sources_1/ip/divider/divider_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'divider'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/mengb/arch/Exp6/Exp6.srcs/sources_1/ip/divider/divider.xci
# IP: The module: 'divider' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/mengb/arch/Exp6/Exp6.srcs/sources_1/ip/divider/divider_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'divider'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
