# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/mengb/arch/Exp6/code/constraint.xdc

# IP: ip/div_gen_0/div_gen_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==div_gen_0 || ORIG_REF_NAME==div_gen_0} -quiet] -quiet

# IP: ip/mult_gen_2/mult_gen_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mult_gen_2 || ORIG_REF_NAME==mult_gen_2} -quiet] -quiet
